### ISSUE TITLE
"Different arrow" for e.g. rmint method

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/ifitlab#24]
Suggestion: Horizontal line rather than bent arrow (indicating this is a 'method' rather than a 'function')

**Comment by jakob-garde** [comment]
Now a double lined, non directional link connects the object and method node centers. A connected method node loses its autonomous movement and follows its owner.

**Comment by jakob-garde** [comment]
Methods now have a straight double-line to their owner object.
