### ISSUE TITLE
Solution to avoid rendering literals

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/ifitlab#25]
This would unclutter a view like 
![safariscreensnapz004](https://user-images.githubusercontent.com/8593355/42816440-1a439e1a-89cb-11e8-8275-034ce1a3d1ed.png)

**Comment by jakob-garde** [comment]
Literals are now much smaller, and snap to the connected node. Literal node labels may need an additional change

**Comment by jakob-garde** [comment]
Literals have been made considerably smaller, and now move with their "object" when it is moved.
