### ISSUE TITLE
Look at options for mouse-over on objects

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/ifitlab#27]
From Mads Bertelsen, minidoc for each type of object / operator etc.

Doxygen or equivalent? Built-in solutions from Python or Google code

**Comment by jakob-garde** [comment]
A doc text is now displayed in the node info panel when clinging on nodes. Mouse-over text is not recommended, since it will get in the way once the user knows how to use the various node types

**Comment by jakob-garde** [comment]
This is probably fine, closing.
