### ISSUE TITLE
maj 2019 tasks, step 1

### ISSUE THREAD

**Issue by jakob-garde** [McStasMcXtrace/ifitlab#32]
idata: 

- subtract data sets (e.g. background) - DONE
- rebin to a certain number of equal bins - DONE
- maybe: rebin using exp bin size, this is used by a few sans people - WONT
- map data points by some function / rescale axis - DONE
- constructor using axis and values from literals - DONE

ifunc:

- exp fit fct - NA (was already possible via iFit native symbol notation)
- vectorized parameter values shown in node inspector - DONE
- fix: vectorized plot data - DONE
- Create Log and Square models as ifuncs - DONE
- Enable construction-time model determination as default parameters - DEFERRED (From_model)

misc:

- fix: idx editor dual mode - DONE
- unpack vectorized data set from sim scan sweep - DONE

**Comment by willend** [comment]
For vectorised data set under misc: here is a recipe:
* On the "scan overview" page for a given monitor e.g. http://sim.e-neutrons.org/static/data/mcstas_SANSsimple_20190502_140437/rdetector_sweep.html , generate a link to rdetector.zip which is a file with the content:
```
mcstas/0/rdetector.dat
mcstas/1/rdetector.dat
mcstas/2/rdetector.dat
mcstas/3/rdetector.dat
```
- generated by the worker process using e.g.
```
find mcstas/ -name rdetector.dat | sort | xargs zip -r rdetector.zip
```

**Comment by willend** [comment]
(And this actually works, see below)
![Screenshot 2019-05-02 at 16 14 25](https://user-images.githubusercontent.com/8593355/57081643-73f90e00-6cf5-11e9-9cf9-d4f209ae368a.png)

**Comment by willend** [comment]
Vectorised dataset support by zip file is now implemented, needs testing @climbcat

**Comment by jakob-garde** [comment]
Very good, I will test that! 

Four new nodes have been added to ifl and uploaded to elearn1, where the case has been sketched out.

![image](https://user-images.githubusercontent.com/11196009/57366051-83a9a400-7186-11e9-93bd-478c7f8700a7.png)

**Comment by jakob-garde** [comment]
@willend 
I have tested the .zip method as you requested above. If I run MATLAB manually, it works fine, both on my system and on elearn1. However, if I run this functionality through the worker process, I get the same error message in both cases: 

<pre>T2 : idata_dd540157495b4c80a963c2b5209af340 = iData('http://sim.e-neutrons.org/static/data/jaga15_SANSsimpleSpheres_20190513_135017/rdetector.zip');
wget http://sim.e-neutrons.org/static/data/jaga15_SANSsimpleSpheres_20190513_135017/rdetector.zip -O /tmp/tp84994144570907190.zip
iLoad: Can't extract file "/tmp/tp84994144570907190.zip" (unzip).
Warning: Function UNZIP requires Java.
</pre>

And indeed, the zip method does not work when used through the interface. There must be something different on the the virtualized system?

**Comment by jakob-garde** [comment]
status update: 

The following are DONE: 

- subtract data sets (e.g. background)
- vectorized parameter values shown in node inspector
- fix: vectorized plot data

The following are HALF: 

- rebin to a certain number of equal bins
- map data points by some function
- rescale axis (actually, map_axis_1)
- unpack vectorized data set from sim scan sweep

The following are suggested SKIP:

- maybe: rebin using exp bin size, this is used by a few sans people
- fix: idx editor dual mode

**Comment by jakob-garde** [comment]
The following are new:

- Create Log and Square models as ifuncs
- Enable construction-time model determination as default parameters

**Comment by jakob-garde** [comment]
Log and Square axis/signal IData->IData mappings ("operators") have been created, and the map and map_axis functions have been discarded in favour of a From_model.

**Comment by jakob-garde** [comment]
rebin iFit code approximately: <code>b=interp(a, new_axis)</code> , where <code>new_axis=linspace(min(getaxis(a,axis)),max(getaxis(a,axis)),newbins)</code> for axis=1, 2, ...

**Comment by jakob-garde** [comment]
Most of the tasks have been done and implemented, this task can be closed.
