### ISSUE TITLE
Log in with user credentials

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/ifitlab#6]
DB backend / django session

**Comment by jakob-garde** [comment]
Info: 

There is one python memory space for every "uwsgi process" (see uwsgi_ifl.ini). If we increase the processes beyond one, we need some sort of memory sharing OR synchronization mechanism - through the db, persistent manually started memory space, etc..

**Comment by jakob-garde** [comment]
Basically this:

https://stackoverflow.com/questions/1268252/possible-to-share-in-memory-data-between-2-separate-processes

**Comment by jakob-garde** [comment]
- ML variable naming scheme update: for example, seamlessly prefix username to all variables 
- user session expire: clean up server data including all associated ML variables

**Comment by willend** [comment]
DONE, except minor details
