### ISSUE TITLE
Define "result" of an analysis

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/ifitlab#8]
Should show
* Datafiles loaded
* Guesses
* Models fitted
* Parameters

**Comment by jakob-garde** [comment]
- literal nodes, content by label
- all open plots be that data, models or a combination
- output nodes in text/json, by label

e.g.:
1) inputs
2) plots
3) outputs

**Comment by jakob-garde** [comment]
static html?

- includes data "copy2cb" button for every graph

**Comment by jakob-garde** [comment]
iFit log file

**Comment by willend** [comment]
Consider if this is not already fulfilled by availability of 
![safariscreensnapz162](https://user-images.githubusercontent.com/8593355/42816677-e3160c7e-89cb-11e8-9686-8fdaff6549fe.png)

**Comment by jakob-garde** [comment]
It probably is, closing.
